Add gh binary

diff --git a/install/install-gh b/install/install-gh
--- a/install/install-gh
+++ b/install/install-gh
@@ -1,7 +1,33 @@
 #!/bin/sh
 
-sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
-sudo apt-add-repository https://cli.github.com/packages
-sudo apt update
-sudo apt install gh
+# ubuntu/debian only
+#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
+#sudo apt-add-repository https://cli.github.com/packages
+#sudo apt update
+#sudo apt install gh
 
+# identify release
+export V=`curl  "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c2-` # FIX the shitty subprocs
+
+if [ -z "${V}" ];then
+    echo Could not determine version.
+    exit 1
+fi
+
+# fetch release
+curl -sSL https://github.com/cli/cli/releases/download/v${V}/gh_${V}_linux_amd64.tar.gz -o gh_${V}_linux_amd64.tar.gz
+
+if [ ! -e "gh_${V}_linux_amd64.tar.gz" ];then
+    echo Could not curl down the release tar ball
+    exit 1
+fi
+
+# extract
+tar xvf gh_${V}_linux_amd64.tar.gz
+
+# install
+mkdir -p "${HOME}/.local/bin"
+cp gh_${V}_linux_amd64/bin/gh "${HOME}/.local/bin"
+
+# cleanup
+rm -rf gh_${V}_linux_amd64 gh_${V}_linux_amd64.tar.gz
