Remove wasteful cd aliases and add work merge

diff --git a/scripts/work b/scripts/work
--- a/scripts/work
+++ b/scripts/work
@@ -1,5 +1,5 @@
 #!/bin/sh
-#set -x # for debugging
+set -x # for debugging
 set -e
 
 # Manage Git repos as worktrees that are contained in peer directories
@@ -22,6 +22,12 @@ set -e
 #
 # * If two args and first is `rm` or `remove` prompt for confirmation
 #   and remove worktree *and* branch.
+#
+# * If first arg is `merge` will prompt to merge current worktree into
+#   main and remove itself.
+#
+# Note that there is no need to close tickets because that can simply be
+# done by including references to them in the commit messages.
 
 CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/work"
 
@@ -59,14 +65,32 @@ add)
 	echo "$PWD" >"$CACHE/last"
 	echo "$PWD"
 	;;
+merge)
+	dir=${2:-$(pdhas -f .git)}
+	dir=${dir%.git}
+	cd "$dir"
+	branch="$(pwdname)"
+	if test -z "$branch"; then
+		echo "Could not determine worktree to merge." >&2
+		exit 1
+	fi
+	cd "$(/tmp/work main)"
+	git merge "$branch"
+	/tmp/work rm "$branch"
+	;;
 list | ls) git worktree list ;;
+main)
+	git worktree list >/dev/null 2>&1 # just for the failure check
+	path=$(git worktree list | head -1)
+	echo ${path%% *}
+	;;
 rm | remove)
 	branch="${2:-$(pwdname)}"
 	read -p "Really remove $branch? " answer
 	test "$answer" != y && echo "Okay." && exit 0
 	git push origin --delete "$branch" || true
-	git worktree remove "$branch"
-	git branch -d "$branch"
+	git worktree remove -f "$branch"
+	git branch -d "$branch" -f
 	;;
 last | "") head -1 "$CACHE/last" 2>/dev/null ;;
 *) usage ;;
